# This is a basic workflow to help you get started with Actions

name: Rollback

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # # Primer paso:Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Asegurarnos de tener al menos dos commits en el historial

      # Segundo paso: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '14'

      # Tercer paso: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Cuarto paso: Ejecutar pruebas
      - name: Run tests
        run: npm test

      - name: Rollback if deployment failed
        if: failure()
        run: |
          echo "Deployment failed. Rolling back to the previous version..."
          # Solo rollback si hay al menos dos commits
          if [ "$(git rev-list --count HEAD)" -gt 1 ]; then
            git reset --hard HEAD^
            git push origin master --force
            echo "Rollback completed successfully"
          else
            echo "Not enough commits to roll back. Rollback not performed."
          fi
